spring.application.name=MySmartRecipeBook

#mongoDB connection
spring.data.mongodb.uri=mongodb://10.1.1.92:27017,10.1.1.90:27017,10.1.1.91:27017/MySmartRecipeBookDB?replicaSet=rs0

#cluster nodes
app.redis.cluster.nodes=10.1.1.90:7004,10.1.1.91:7004,10.1.1.92:7004
#database index (default = 0)
spring.data.redis.database=0
#spring.data.redis.password


#parameters
app.recipe.pag-size-title=5
app.recipe.pag-size-category=10
app.recipe.pag-size-home=5
app.recipe.pag-size-chef=5
app.recipe.pag-size-foodie=5

app.recipe.do-population=false
app.recipe.do-chef-recipes=false
app.recipe.do-neo4j-population=true
app.recipe.do-redis-population=true
#Neo4j connection
spring.neo4j.uri=bolt://10.1.1.90:7687
#spring.neo4j.authentication.username=neo4j
#spring.neo4j.authentication.password=12345678


app.jwt.secret=MyVeryLongAndSecureJwtSecretKeyThatMustBeAtLeast32Characters
#token duration: 24h
app.jwt.expirationMs=86400000

#exception message
server.error.include-message=always
server.error.include-stacktrace=never

#mongo indexes
spring.data.mongodb.auto-index-creation=true

#TODO: da controllare
#extra
spring.main.allow-circular-references=true