package it.unipi.MySmartRecipeBook.utils;

import it.unipi.MySmartRecipeBook.dto.ChefInfoDTO;
import it.unipi.MySmartRecipeBook.dto.recipe.ChefPreviewRecipeDTO;
import it.unipi.MySmartRecipeBook.model.Chef;
import it.unipi.MySmartRecipeBook.model.Mongo.AdminRecipe;
import it.unipi.MySmartRecipeBook.model.Mongo.ChefRecipe;
import org.springframework.stereotype.Component;

@Component
public class ChefConvertions {

    /* Function to create a ChefInfoDTO from a Chef entity */

    public ChefInfoDTO chefToChefInfo(Chef chef){

        return new ChefInfoDTO(
                chef.getUsername(),
                chef.getName(),
                chef.getSurname(),
                chef.getEmail(),
                chef.getBirthdate()
        );
    }


    /* Function to create a ChefRecipe from an AdmiRecipe. To be more specific, we have an
    additional field "NumSaves" that counts how many foodies has saved that specific recipe.
    In addition, we remove all the informations about the chef that would have been redundant.
    */

    public ChefRecipe adminToChefRecipe (AdminRecipe recipe){

        ChefRecipe full_recipe = new ChefRecipe();
        full_recipe.setId(recipe.getId());
        full_recipe.setTitle(recipe.getTitle());
        full_recipe.setPresentation(recipe.getPresentation());
        full_recipe.setCategory(recipe.getCategory());
        full_recipe.setPrepTime(recipe.getPrepTime());
        full_recipe.setPreparation(recipe.getPreparation());
        full_recipe.setDifficulty(recipe.getDifficulty());
        full_recipe.setImageURL(recipe.getImageURL());
        full_recipe.setIngredients(recipe.getIngredients());
        full_recipe.setCreationDate(recipe.getCreationDate());
        full_recipe.setNumSaves(0);

        return full_recipe;
    }


    /* Function to create a ChefPreviewRecipeDTO from an AdminRecipe*/

    public ChefPreviewRecipeDTO adminToChefDTO (AdminRecipe recipe){

        ChefPreviewRecipeDTO recipeDTO = new ChefPreviewRecipeDTO();

        /* In this case the id is the temporary one (not the one generated by Mongo) since the recipe has not
        been inserted in the recipes collection yet */
        recipeDTO.setId(recipe.getId());
        recipeDTO.setTitle(recipe.getTitle());
        recipeDTO.setPresentation(recipe.getPresentation());
        recipeDTO.setImageURL(recipe.getImageURL());
        recipeDTO.setCreationDate(recipe.getCreationDate().toLocalDate());

        return recipeDTO;
    }

}
