package it.unipi.MySmartRecipeBook.utils;

import it.unipi.MySmartRecipeBook.dto.users.RegistedUserInfoDTO;
import it.unipi.MySmartRecipeBook.dto.recipe.ChefPreviewRecipeDTO;
import it.unipi.MySmartRecipeBook.model.Chef;
import it.unipi.MySmartRecipeBook.model.Mongo.BaseRecipe;
import it.unipi.MySmartRecipeBook.model.Mongo.ChefRecipe;
import it.unipi.MySmartRecipeBook.model.Mongo.RecipeMongo;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class ChefConvertions {

    /* Function to create a ChefInfoDTO from a Chef entity */

    public RegistedUserInfoDTO chefToChefInfo(Chef chef){

        return new RegistedUserInfoDTO(
                chef.getUsername(),
                chef.getName(),
                chef.getSurname(),
                chef.getEmail(),
                chef.getBirthdate()
        );
    }


    /* Function to create a ChefRecipe from an AdmiRecipe. To be more specific, we have an
    additional field "NumSaves" that counts how many foodies has saved that specific recipe.
    In addition, we remove all the informations about the chef that would have been redundant.
    */

    public ChefRecipe recipeToChefRecipe (BaseRecipe recipe){

        ChefRecipe full_recipe = new ChefRecipe();
        full_recipe.setId(recipe.getId());
        full_recipe.setTitle(recipe.getTitle());
        full_recipe.setPresentation(recipe.getPresentation());
        full_recipe.setCategory(recipe.getCategory());
        full_recipe.setPrepTime(recipe.getPrepTime());
        full_recipe.setPreparation(recipe.getPreparation());
        full_recipe.setDifficulty(recipe.getDifficulty());
        full_recipe.setImageURL(recipe.getImageURL());
        full_recipe.setIngredients(recipe.getIngredients());
        full_recipe.setCreationDate(recipe.getCreationDate());
        full_recipe.setNumSaves(0);

        return full_recipe;
    }


    /* Function to create a ChefPreviewRecipeDTO from an AdminRecipe*/

    public ChefPreviewRecipeDTO adminToChefDTO (BaseRecipe recipe){

        ChefPreviewRecipeDTO recipeDTO = new ChefPreviewRecipeDTO();

        /* In this case the id is the temporary one (not the one generated by Mongo) since the recipe has not
        been inserted in the recipes collection yet */
        recipeDTO.setId(recipe.getId());
        recipeDTO.setTitle(recipe.getTitle());
        recipeDTO.setImageURL(recipe.getImageURL());
        recipeDTO.setCreationDate(recipe.getCreationDate().toLocalDate());

        return recipeDTO;
    }

    public List<ChefRecipe> MongoListToChefList(List<RecipeMongo> recipesToConvert) {

        List<ChefRecipe> chefRecipes = new ArrayList<>();

        for(RecipeMongo recipeMongo : recipesToConvert){
            ChefRecipe recipe = new ChefRecipe();

            recipe.setId(recipeMongo.getId());
            recipe.setTitle(recipeMongo.getTitle());
            recipe.setPresentation(recipeMongo.getPresentation());
            recipe.setCategory(recipeMongo.getCategory());
            recipe.setPrepTime(recipeMongo.getPrepTime());
            recipe.setPreparation(recipeMongo.getPreparation());
            recipe.setDifficulty(recipeMongo.getDifficulty());
            recipe.setImageURL(recipeMongo.getImageURL());
            recipe.setIngredients(recipeMongo.getIngredients());
            recipe.setCreationDate(recipeMongo.getCreationDate());
            recipe.setNumSaves(recipe.getNumSaves());

            chefRecipes.add(recipe);
        }

        return chefRecipes;
    }


    public List<ChefPreviewRecipeDTO> ChefListToSummaryList(List<ChefRecipe> recipesList) {

        List<ChefPreviewRecipeDTO> chefPreviewList = new ArrayList<>();
        for(ChefRecipe recipe : recipesList){
            ChefPreviewRecipeDTO recipeDTO = new ChefPreviewRecipeDTO();

            recipeDTO.setId(recipe.getId());
            recipeDTO.setTitle(recipe.getTitle());
            recipeDTO.setImageURL(recipe.getImageURL());
            recipeDTO.setCreationDate(recipe.getCreationDate().toLocalDate());
            chefPreviewList.add(recipeDTO);
        }

        return  chefPreviewList;
    }

    public List<ChefPreviewRecipeDTO> MongoListToChefPreview(List<RecipeMongo> recipesToConvert) {

        List<ChefPreviewRecipeDTO> chefRecipes = new ArrayList<>();

        for(RecipeMongo recipeMongo : recipesToConvert){
            ChefPreviewRecipeDTO recipe = new ChefPreviewRecipeDTO();

            recipe.setId(recipeMongo.getId());
            recipe.setTitle(recipeMongo.getTitle());
            recipe.setImageURL(recipeMongo.getImageURL());
            recipe.setCreationDate(recipeMongo.getCreationDate().toLocalDate());
            chefRecipes.add(recipe);
        }

        return chefRecipes;
    }
}
