package it.unipi.MySmartRecipeBook.utils;

import it.unipi.MySmartRecipeBook.dto.recipe.CreateRecipeDTO;
import it.unipi.MySmartRecipeBook.dto.users.RegistedUserDTO;
import it.unipi.MySmartRecipeBook.dto.users.RegistedUserInfoDTO;
import it.unipi.MySmartRecipeBook.dto.recipe.ChefPreviewRecipeDTO;
import it.unipi.MySmartRecipeBook.model.Chef;
import it.unipi.MySmartRecipeBook.model.Mongo.BaseRecipe;
import it.unipi.MySmartRecipeBook.model.Mongo.ChefRecipe;
import it.unipi.MySmartRecipeBook.model.Mongo.ChefRecipeSummary;
import it.unipi.MySmartRecipeBook.model.Mongo.RecipeMongo;
import it.unipi.MySmartRecipeBook.model.ReducedChef;
import it.unipi.MySmartRecipeBook.security.UserPrincipal;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Component
public class ChefUtilityFunctions {

    private final PasswordEncoder passwordEncoder;

    public ChefUtilityFunctions(PasswordEncoder passwordEncoder) {
        this.passwordEncoder = passwordEncoder;
    }


    // Nel momento in cui un utente compila il form per la registrazione, affinchè possa essere effettivamente registrato
    // dobbiamo criptare la password e aggiungere la data di registrazione
    public Chef createChefEntity (RegistedUserDTO dto){

        Chef chef = new Chef();
        chef.setUsername(dto.getUsername());
        chef.setName(dto.getName());
        chef.setSurname(dto.getSurname());

        chef.setEmail(dto.getEmail());
        chef.setPassword(passwordEncoder.encode(dto.getPassword()));

        chef.setBirthdate(dto.getBirthdate());
        chef.setRegistrationDate(LocalDate.now());

        return chef;
    }


    // Prendiamo le informazioni da mostrare nell'area personale dello chef a partire dall'entità Chef in MongoDB
    // (in particolare non mostriamo la password per questioni di sicurezza)

    public RegistedUserInfoDTO chefToChefInfo(Chef chef){

        return new RegistedUserInfoDTO(
                chef.getUsername(),
                chef.getName(),
                chef.getSurname(),
                chef.getEmail(),
                chef.getBirthdate()
        );
    }

    // Ricetta che viene creata nel momento in cui uno chef fa submit del form compilato con tutte le informazioni
    // necessarie per l'inserimento di una ricetta
    public BaseRecipe createBaseRecipe (CreateRecipeDTO dto){

        BaseRecipe recipe = new BaseRecipe();
        recipe.setId(java.util.UUID.randomUUID().toString());
        recipe.setTitle(dto.getTitle());
        recipe.setCategory(dto.getCategory());
        recipe.setPreparation(dto.getPreparation());
        recipe.setPrepTime(dto.getPrepTime());
        recipe.setDifficulty(dto.getDifficulty());
        recipe.setPresentation(dto.getPresentation());
        recipe.setImageURL(dto.getImageURL());
        recipe.setIngredients(dto.getIngredients());
        recipe.setCreationDate(LocalDateTime.now());

        ReducedChef chef = new ReducedChef();
        UserPrincipal chef1 = (UserPrincipal) SecurityContextHolder.getContext()
                .getAuthentication()
                .getPrincipal();
        chef.setId(chef1.getId());
        chef.setName(chef1.getName());
        chef.setSurname(chef1.getSurname());

        recipe.setChef(chef);

        return recipe;
    }


    /* Function to create a ChefRecipe from a BaseRecipe. To be more specific, we have an
    additional field "NumSaves" that counts how many foodies has saved that specific recipe.
    In addition, we remove all the informations about the chef that would have been redundant.
    */

    public ChefRecipe recipeToChefRecipe (BaseRecipe recipe){

        ChefRecipe full_recipe = new ChefRecipe();
        full_recipe.setId(recipe.getId());
        full_recipe.setTitle(recipe.getTitle());
        full_recipe.setPresentation(recipe.getPresentation());
        full_recipe.setCategory(recipe.getCategory());
        full_recipe.setPrepTime(recipe.getPrepTime());
        full_recipe.setPreparation(recipe.getPreparation());
        full_recipe.setDifficulty(recipe.getDifficulty());
        full_recipe.setImageURL(recipe.getImageURL());
        full_recipe.setIngredients(recipe.getIngredients());
        full_recipe.setCreationDate(recipe.getCreationDate());
        full_recipe.setNumSaves(0);

        return full_recipe;
    }


    /* Function to create a ChefPreviewRecipeDTO from an AdminRecipe*/

    public ChefPreviewRecipeDTO baseToChefDTO(BaseRecipe recipe){

        ChefPreviewRecipeDTO recipeDTO = new ChefPreviewRecipeDTO();

        /* In this case the id is the temporary one (not the one generated by Mongo) since the recipe has not
        been inserted in the recipes collection yet */
        recipeDTO.setId(recipe.getId());
        recipeDTO.setTitle(recipe.getTitle());
        recipeDTO.setImageURL(recipe.getImageURL());
        recipeDTO.setCreationDate(recipe.getCreationDate().toLocalDate());

        return recipeDTO;
    }

    public List<ChefRecipeSummary> MongoListToChefListSummary(List<RecipeMongo> recipesToConvert) {

        List<ChefRecipeSummary> chefRecipes = new ArrayList<>();

        for(RecipeMongo recipeMongo : recipesToConvert){
            ChefRecipeSummary recipe = new ChefRecipeSummary();

            recipe.setId(recipeMongo.getId());
            recipe.setTitle(recipeMongo.getTitle());
            recipe.setImageURL(recipeMongo.getImageURL());
            recipe.setCreationDate(recipeMongo.getCreationDate());
            recipe.setNumSaves(recipe.getNumSaves());

            chefRecipes.add(recipe);
        }

        return chefRecipes;
    }


    public List<ChefPreviewRecipeDTO> ChefListToSummaryList(List<ChefRecipeSummary> recipesList) {

        List<ChefPreviewRecipeDTO> chefPreviewList = new ArrayList<>();
        for(ChefRecipeSummary recipe : recipesList){
            ChefPreviewRecipeDTO recipeDTO = new ChefPreviewRecipeDTO();

            recipeDTO.setId(recipe.getId());
            recipeDTO.setTitle(recipe.getTitle());
            recipeDTO.setImageURL(recipe.getImageURL());
            recipeDTO.setCreationDate(recipe.getCreationDate().toLocalDate());
            recipeDTO.setNumSaves(recipe.getNumSaves());

            chefPreviewList.add(recipeDTO);
        }

        return  chefPreviewList;
    }

    public List<ChefPreviewRecipeDTO> MongoListToChefPreview(List<RecipeMongo> recipesToConvert) {

        List<ChefPreviewRecipeDTO> chefRecipes = new ArrayList<>();

        for(RecipeMongo recipeMongo : recipesToConvert){
            ChefPreviewRecipeDTO recipe = new ChefPreviewRecipeDTO();

            recipe.setId(recipeMongo.getId());
            recipe.setTitle(recipeMongo.getTitle());
            recipe.setImageURL(recipeMongo.getImageURL());
            recipe.setCreationDate(recipeMongo.getCreationDate().toLocalDate());
            chefRecipes.add(recipe);
        }

        return chefRecipes;
    }

    public boolean chefAlreadyInserted(Chef targetChef, Chef chef) {

        return  targetChef.getName().equals(chef.getName()) &&
                targetChef.getSurname().equals(chef.getSurname()) &&
                targetChef.getBirthdate().equals(chef.getBirthdate());
    }


}
